FROM python:3.6.13

# Open CV Dependancies
RUN apt-get update 
RUN apt-get install -y \
                  ffmpeg \
                  libsm6 \
                  libxext6
# Install git                  
RUN apt-get install -y git
# Set working dir
WORKDIR /code

# Install packages
COPY requirements*.txt /code/
RUN pip3 install -r requirements.txt 

# Copy code
COPY ./src /code

# For automatic download data via dvc
ADD . /app
#VOLUME /voldata
WORKDIR /app

# Download data
RUN dvc remote modify storage access_key_id '${KEY_ID}'
RUN dvc remote modify storage secret_access_key '${SECRET_KEY}'
RUN dvc pull

# Init
RUN python3 setup.py build_ext --inplace

